root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/goseinaka-server"
 # For GoSeinaka, the main package is in 'cmd/goseinaka-server/main.go'.
 # The output binary will be named 'goseinaka-server' (or as specified by -o)
 # and placed in the 'tmp_dir'.
  cmd = "go build -o ./tmp/goseinaka-server ./cmd/goseinaka-server/main.go"
 # Delay in milliseconds before triggering a build after a file change.
 # Useful to batch multiple quick saves.
  delay = 2000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = true # If true, 'air's console output will include timestamps.

[misc]
  clean_on_exit = true # if you want the console cleared.

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = true # clear console
  keep_scroll = true
